version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
